services:
  user-service:
    container_name: ms-user
    build:
      context: ../modules/user-service
      dockerfile: ../../docker/Dockerfile
      args:
        SERVICE_NAME: user-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      LOKI_URL: http://loki:3100
    restart: always
    ports:
      - "8010:8010"
    depends_on:
      - users_postgresql
      - kafka
      - keycloak
    networks:
      - microservices-net

  notification-service:
    container_name: ms-notification
    build:
      context: ../modules/notification-service
      dockerfile: ../../docker/Dockerfile
      args:
        SERVICE_NAME: notification-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      LOKI_URL: http://loki:3100
    restart: always
    ports:
      - "8020:8020"
    depends_on:
      - kafka
    networks:
      - microservices-net

  discovery-service:
    container_name: ms-discovery
    build:
      context: ../modules/discovery-service
      dockerfile: ../../docker/Dockerfile
      args:
        SERVICE_NAME: discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      LOKI_URL: http://loki:3100
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  users_postgresql:
    container_name: ms_users_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      PGDATA: /var/lib/postgresql/data
    volumes:
      - users_psql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak-ms
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgre_keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: "true"
    volumes:
      - ../realm.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgre_keycloak
    networks:
      - microservices-net

  postgre_keycloak:
    container_name: keycloak_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak_db
      PGDATA: /data/postgres
    volumes:
      - postgres_keycloak:/data/postgres
    ports:
      - "5555:5432"
    restart: unless-stopped
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net

  kafka:
    container_name: ms_kafka
    image: confluentinc/cp-kafka:7.2.15
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ms_kafka:9092
    networks:
      - microservices-net

  kafka_ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: "no"
    ports:
      - "8989:8180"
    environment:
      SERVER_PORT: 8180
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ms_kafka:9092
    networks:
      - microservices-net
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8180/actuator/health || exit -1
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
    depends_on:
      - kafka
      - zookeeper

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - ../log-directory/victoria-metrics/promscrape.yml:/victoria-metrics/promscrape.yml
    networks:
      - microservices-net
    command:
      - '--promscrape.config=/victoria-metrics/promscrape.yml'
      - '--promscrape.config.strictParse=false'

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    volumes:
      - ../log-directory/grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    networks:
      - microservices-net

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    volumes:
      - ../log-directory/loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - microservices-net

  tempo:
    container_name: tempo
    image: grafana/tempo:2.6.0
    command: [ "-config.file=/etc/tempo-config.yml" ]
    volumes:
      - ../log-directory/tempo/tempo-config.yml:/etc/tempo-config.yml
    ports:
      - "14268:14268"
      - "3200:3200"
      - "55680:55680"
      - "55681:55681"
      - "9411:9411"
      - "4318:4318"
      - "4317:4317"
    networks:
      - microservices-net


networks:
  microservices-net:
    driver: bridge

volumes:
  users_psql:
  postgres_keycloak: